# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d808ac9fc67fddd079146a0709c33a0d2ce1d6ff65b654b762a4170b25173716d35711e90b8de1d968100ee1abf3fec5f2e8d8d993a73d709a8d5c3ea936b1

test:
  secret_key_base: 24c915690958428a474fae25954f6369e3d46ebf807ba04aef7c4be66a297d77f2b19a7c5112c6ea95559762b93e61dbe782f0cbbe63a12044e016930d95a9e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
